public struct AttributeKey: RawRepresentable, Codable, Hashable, Sendable {
  public let rawValue: String

  public init(_ value: String) {
    self.rawValue = value
  }
  
  public init(rawValue: String) {
    self.rawValue = rawValue
  }
}

public extension AttributeKey {
  static let `id` = AttributeKey("id")
  static let nodeId = AttributeKey("nodeId")
  static let context = AttributeKey("context")
  static let type = AttributeKey("type")
  static let name = AttributeKey("name")
  static let value = AttributeKey("value")
  static let oldValue = AttributeKey("oldValue")
  static let url = AttributeKey("url")
  static let bundle = AttributeKey("bundle")
  static let message = AttributeKey("message")
  static let systemName = AttributeKey("systemName")
  static let enabled = AttributeKey("enabled")
  static let isActive = AttributeKey("isActive")
  static let pattern = AttributeKey("pattern")
  static let attributes = AttributeKey("attributes")
  static let inherit = AttributeKey("inherit")
  static let style = AttributeKey("style")
  static let count = AttributeKey("count")
  static let span = AttributeKey("span")
  static let edge = AttributeKey("edge")
  static let edges = AttributeKey("edges")
  static let visibility = AttributeKey("visibility")
  static let behavior = AttributeKey("behavior")

  static let text = AttributeKey("text")
  static let oldText = AttributeKey("oldText")
  static let title = AttributeKey("title")
  static let label = AttributeKey("label")
  static let header = AttributeKey("header")
  static let footer = AttributeKey("footer")
  static let weight = AttributeKey("weight")
  static let markdown = AttributeKey("markdown")
  static let design = AttributeKey("design")
  static let size = AttributeKey("size")
  static let fixedSize = AttributeKey("fixedSize")
  static let relativeTo = AttributeKey("relativeTo")
  static let total = AttributeKey("total")
  static let currentValue = AttributeKey("currentValue")
  static let tag = AttributeKey("tag")
  static let tabItem = AttributeKey("tabItem")
  static let badge = AttributeKey("badge")
  static let tabViewStyle = AttributeKey("tabViewStyle")
  static let textFieldStyle = AttributeKey("textFieldStyle")
  static let buttonStyle = AttributeKey("buttonStyle")
  static let progressViewStyle = AttributeKey("progressViewStyle")
  static let listStyle = AttributeKey("listStyle")
  static let listRowBackground = AttributeKey("listRowBackground")
  static let listRowInsets = AttributeKey("listRowInsets")
  static let listRowSeparator = AttributeKey("listRowSeparator")
  static let toggleStyle = AttributeKey("toggleStyle")

  // Internal attribute: when true, NodeView skips .equatable() wrapper
  // Used for modifiers that don't work through .equatable() (e.g., list row modifiers)
  static let ignoreEquatable = AttributeKey("ignoreEquatable")
  static let pickerStyle = AttributeKey("pickerStyle")
  static let labelsHidden = AttributeKey("labelsHidden")
  static let buttonBorderShape = AttributeKey("buttonBorderShape")

  // Gradient properties
  static let colors = AttributeKey("colors")
  static let colorStops = AttributeKey("colorStops")
  static let startPoint = AttributeKey("startPoint")
  static let endPoint = AttributeKey("endPoint")

  static let padding = AttributeKey("padding")
  static let resizable = AttributeKey("resizable")
  static let frame = AttributeKey("frame")
  static let containerRelativeFrame = AttributeKey("containerRelativeFrame")
  static let horizontal = AttributeKey("horizontal")
  static let vertical = AttributeKey("vertical")
  
  // Text modifiers
  static let font = AttributeKey("font")
  static let bold = AttributeKey("bold")
  static let italic = AttributeKey("italic")
  static let underline = AttributeKey("underline")
  static let strikethrough = AttributeKey("strikethrough")
  static let kerning = AttributeKey("kerning")
  static let tracking = AttributeKey("tracking")
  static let lineSpacing = AttributeKey("lineSpacing")
  static let fontWeight = AttributeKey("fontWeight")
  static let foregroundColor = AttributeKey("foregroundColor")
  static let lineLimit = AttributeKey("lineLimit")
  static let multilineTextAlignment = AttributeKey("multilineTextAlignment")
  static let textSelection = AttributeKey("textSelection")
  static let truncationMode = AttributeKey("truncationMode")
  static let minimumScaleFactor = AttributeKey("minimumScaleFactor")
  static let allowsTightening = AttributeKey("allowsTightening")
  static let baselineOffset = AttributeKey("baselineOffset")

  // General modifiers
  static let backgroundColor = AttributeKey("backgroundColor")
  static let background = AttributeKey("background")
  static let dark = AttributeKey("dark")
  static let light = AttributeKey("light")
  static let overlay = AttributeKey("overlay")
  static let mask = AttributeKey("mask")
  static let clipShape = AttributeKey("clipShape")
  static let fill = AttributeKey("fill")
  static let stroke = AttributeKey("stroke")
  static let trim = AttributeKey("trim")
  static let from = AttributeKey("from")
  static let to = AttributeKey("to")
  static let border = AttributeKey("border")
  static let lineWidth = AttributeKey("lineWidth")
  static let color = AttributeKey("color")
  static let tint = AttributeKey("tint")
  static let colorScheme = AttributeKey("colorScheme")
  static let colorSchemeConditional = AttributeKey("colorSchemeConditional")
  static let preferredColorScheme = AttributeKey("preferredColorScheme")
  static let responsive = AttributeKey("responsive")
  static let shadow = AttributeKey("shadow")
  static let blur = AttributeKey("blur")
  static let brightness = AttributeKey("brightness")
  static let contrast = AttributeKey("contrast")
  static let saturation = AttributeKey("saturation")
  static let grayscale = AttributeKey("grayscale")
  static let hueRotation = AttributeKey("hueRotation")
  static let colorInvert = AttributeKey("colorInvert")
  static let luminanceToAlpha = AttributeKey("luminanceToAlpha")
  static let colorMultiply = AttributeKey("colorMultiply")
  static let renderingMode = AttributeKey("renderingMode")
  static let opacity = AttributeKey("opacity")
  static let blendMode = AttributeKey("blendMode")
  static let opaque = AttributeKey("opaque")
  static let hidden = AttributeKey("hidden")
  static let redacted = AttributeKey("redacted")
  static let privacySensitive = AttributeKey("privacySensitive")
  static let cornerRadius = AttributeKey("cornerRadius")
  static let clipped = AttributeKey("clipped")
  static let ignoresSafeArea = AttributeKey("ignoresSafeArea")
  static let safeAreaInset = AttributeKey("safeAreaInset")
  static let location = AttributeKey("location")

  // Layout modifiers (HStack/VStack/ZStack/ScrollView)
  static let spacing = AttributeKey("spacing")
  static let horizontalSpacing = AttributeKey("horizontalSpacing")
  static let verticalSpacing = AttributeKey("verticalSpacing")
  static let alignment = AttributeKey("alignment")
  static let axis = AttributeKey("axis")
  static let scrollBounceBehavior = AttributeKey("scrollBounceBehavior")
  static let scrollTargetBehavior = AttributeKey("scrollTargetBehavior")
  static let scrollTargetLayout = AttributeKey("scrollTargetLayout")
  static let scrollDisabled = AttributeKey("scrollDisabled")
  static let scrollIndicators = AttributeKey("scrollIndicators")
  static let aspectRatio = AttributeKey("aspectRatio")
  static let ratio = AttributeKey("ratio")
  static let contentMode = AttributeKey("contentMode")
  static let offset = AttributeKey("offset")
  static let position = AttributeKey("position")
  static let rotationEffect = AttributeKey("rotationEffect")
  static let rotation3DEffect = AttributeKey("rotation3DEffect")
  static let perspective = AttributeKey("perspective")
  static let scaleEffect = AttributeKey("scaleEffect")
  static let gridCellColumns = AttributeKey("gridCellColumns")
  static let columns = AttributeKey("columns")
  static let rows = AttributeKey("rows")
  static let layoutPriority = AttributeKey("layoutPriority")
  static let coordinateSpace = AttributeKey("coordinateSpace")

  // Frame properties
  static let width = AttributeKey("width")
  static let minWidth = AttributeKey("minWidth")
  static let maxWidth = AttributeKey("maxWidth")
  static let idealWidth = AttributeKey("idealWidth")
  
  static let height = AttributeKey("height")
  static let minHeight = AttributeKey("minHeight")
  static let maxHeight = AttributeKey("maxHeight")
  static let idealHeight = AttributeKey("idealHeight")

  // Padding properties
  static let top = AttributeKey("top")
  static let leading = AttributeKey("leading")
  static let bottom = AttributeKey("bottom")
  static let trailing = AttributeKey("trailing")

  // Corner properties
  static let topLeading = AttributeKey("topLeading")
  static let topTrailing = AttributeKey("topTrailing")
  static let bottomLeading = AttributeKey("bottomLeading")
  static let bottomTrailing = AttributeKey("bottomTrailing")

  static let radius = AttributeKey("radius")
  static let startRadius = AttributeKey("startRadius")
  static let endRadius = AttributeKey("endRadius")
  static let startAngle = AttributeKey("startAngle")
  static let endAngle = AttributeKey("endAngle")
  static let x = AttributeKey("x")
  static let y = AttributeKey("y")
  static let z = AttributeKey("z")
  static let anchor = AttributeKey("anchor")
  static let anchorZ = AttributeKey("anchorZ")
  static let center = AttributeKey("center")
  static let degrees = AttributeKey("degrees")
  static let radians = AttributeKey("radians")
  static let angle = AttributeKey("angle")
  static let zero = AttributeKey("zero")

  // Interaction modifiers
  static let onTap = AttributeKey("onTap")
  static let onTapGesture = AttributeKey("onTapGesture")
  static let onLongPressGesture = AttributeKey("onLongPressGesture")
  static let minimumDuration = AttributeKey("minimumDuration")
  static let onAppear = AttributeKey("onAppear")
  static let onDisappear = AttributeKey("onDisappear")
  static let disabled = AttributeKey("disabled")

  // Animation
  static let animation = AttributeKey("animation")
  static let attribute = AttributeKey("attribute")
  static let next = AttributeKey("next")

  // Animation parameters
  static let duration = AttributeKey("duration")
  static let delay = AttributeKey("delay")
  static let speed = AttributeKey("speed")
  static let response = AttributeKey("response")
  static let dampingFraction = AttributeKey("dampingFraction")
  static let blendDuration = AttributeKey("blendDuration")
  static let autoreverses = AttributeKey("autoreverses")

  // Navigation modifiers
  static let sheet = AttributeKey("sheet")
  static let fullScreenCover = AttributeKey("fullScreenCover")
  static let alert = AttributeKey("alert")
  static let confirmationDialog = AttributeKey("confirmationDialog")
  static let popover = AttributeKey("popover")
  static let navigationDestination = AttributeKey("navigationDestination")
  static let navigationDestinations = AttributeKey("navigationDestinations")
  static let toolbar = AttributeKey("toolbar")
  static let navigationDestinationKey = AttributeKey("navigationDestinationKey")
  static let navigationTitle = AttributeKey("navigationTitle")
  static let navigationBarTitleDisplayMode = AttributeKey("navigationBarTitleDisplayMode")
  static let navigationBarHidden = AttributeKey("navigationBarHidden")
  static let navigationBarBackButtonHidden = AttributeKey("navigationBarBackButtonHidden")
  static let content = AttributeKey("content")
  static let presentedId = AttributeKey("presentedId")
  static let isPresented = AttributeKey("isPresented")
  static let onPresented = AttributeKey("onPresented")
  static let onDismiss = AttributeKey("onDismiss")
  static let animated = AttributeKey("animated")
  static let presentationDetents = AttributeKey("presentationDetents")
  static let presentationDragIndicator = AttributeKey("presentationDragIndicator")
  static let interactiveDismissDisabled = AttributeKey("interactiveDismissDisabled")
  static let buttons = AttributeKey("buttons")
  static let role = AttributeKey("role")
  static let action = AttributeKey("action")

  // Accessibility
  static let accessibilityLabel = AttributeKey("accessibilityLabel")
  static let accessibilityHint = AttributeKey("accessibilityHint")
  static let accessibilityValue = AttributeKey("accessibilityValue")
  static let accessibilityHidden = AttributeKey("accessibilityHidden")
  static let accessibilityIdentifier = AttributeKey("accessibilityIdentifier")
  static let accessibilityTraits = AttributeKey("accessibilityTraits")
  static let accessibilityRemoveTraits = AttributeKey("accessibilityRemoveTraits")
  static let accessibilitySortPriority = AttributeKey("accessibilitySortPriority")
  static let accessibilityElement = AttributeKey("accessibilityElement")
  static let accessibilityInputLabels = AttributeKey("accessibilityInputLabels")
  static let accessibilityAction = AttributeKey("accessibilityAction")

  // Form controls
  static let placeholder = AttributeKey("placeholder")
  static let onTextChange = AttributeKey("onTextChange")
  static let onSubmit = AttributeKey("onSubmit")
  static let keyboardType = AttributeKey("keyboardType")
  static let autocapitalization = AttributeKey("autocapitalization")
  static let textContentType = AttributeKey("textContentType")
  static let submitLabel = AttributeKey("submitLabel")
  static let onFocus = AttributeKey("onFocus")
  static let onBlur = AttributeKey("onBlur")
  static let isOn = AttributeKey("isOn")
  static let onToggle = AttributeKey("onToggle")
  static let minimumValue = AttributeKey("minimumValue")
  static let maximumValue = AttributeKey("maximumValue")
  static let currentValueLabel = AttributeKey("currentValueLabel")
  static let minimumValueLabel = AttributeKey("minimumValueLabel")
  static let maximumValueLabel = AttributeKey("maximumValueLabel")
  static let step = AttributeKey("step")
  static let onSliderChange = AttributeKey("onSliderChange")
  static let onStepperChange = AttributeKey("onStepperChange")
  static let onPickerChange = AttributeKey("onPickerChange")
  static let selection = AttributeKey("selection")
  static let isExpanded = AttributeKey("isExpanded")
  static let onExpandedChange = AttributeKey("onExpandedChange")
  static let displayedComponents = AttributeKey("displayedComponents")
  static let minimumDate = AttributeKey("minimumDate")
  static let maximumDate = AttributeKey("maximumDate")
  static let onDateChange = AttributeKey("onDateChange")
  static let locale = AttributeKey("locale")
  static let timeZone = AttributeKey("timeZone")
  static let controlSize = AttributeKey("controlSize")
  static let onColorChange = AttributeKey("onColorChange")
  static let supportsOpacity = AttributeKey("supportsOpacity")

  // Webview
  static let html = AttributeKey("html")
  static let javascriptBridge = AttributeKey("javascriptBridge")
  static let allowlist = AttributeKey("allowlist")
  static let injectionTime = AttributeKey("injectionTime")
  static let mainFrameOnly = AttributeKey("mainFrameOnly")
  static let isScrollEnabled = AttributeKey("isScrollEnabled")
  static let isInspectable = AttributeKey("isInspectable")

  // SceneKit
  static let allowsCameraControl = AttributeKey("allowsCameraControl")
  static let autoenablesDefaultLighting = AttributeKey("autoenablesDefaultLighting")
  static let showsStatistics = AttributeKey("showsStatistics")
  static let addDefaultCamera = AttributeKey("addDefaultCamera")
  static let addDefaultLight = AttributeKey("addDefaultLight")
  static let length = AttributeKey("length")
  static let chamferRadius = AttributeKey("chamferRadius")
  // radius already defined above
  static let topRadius = AttributeKey("topRadius")
  static let bottomRadius = AttributeKey("bottomRadius")
  static let ringRadius = AttributeKey("ringRadius")
  static let pipeRadius = AttributeKey("pipeRadius")
  static let capRadius = AttributeKey("capRadius")
  static let skPosition = AttributeKey("skPosition")
  static let skRotation = AttributeKey("skRotation")
  static let skScale = AttributeKey("skScale")
  static let fieldOfView = AttributeKey("fieldOfView")
  static let zNear = AttributeKey("zNear")
  static let zFar = AttributeKey("zFar")
  static let usesOrthographicProjection = AttributeKey("usesOrthographicProjection")
  static let orthographicScale = AttributeKey("orthographicScale")
  static let lightType = AttributeKey("lightType")
  static let intensity = AttributeKey("intensity")
  static let temperature = AttributeKey("temperature")
  static let castsShadow = AttributeKey("castsShadow")
  static let shadowRadius = AttributeKey("shadowRadius")
  static let shadowColor = AttributeKey("shadowColor")
  static let spotInnerAngle = AttributeKey("spotInnerAngle")
  static let spotOuterAngle = AttributeKey("spotOuterAngle")
  // Material properties
  static let skDiffuse = AttributeKey("skDiffuse")
  static let skSpecular = AttributeKey("skSpecular")
  static let skEmission = AttributeKey("skEmission")
  static let skAmbient = AttributeKey("skAmbient")
  static let skShininess = AttributeKey("skShininess")
  static let skRoughness = AttributeKey("skRoughness")
  static let skMetalness = AttributeKey("skMetalness")
  // Texture properties (for SKTexture node configuration)
  static let textureURL = AttributeKey("textureURL")
  static let textureBundle = AttributeKey("textureBundle")
  static let textureWrapS = AttributeKey("textureWrapS")
  static let textureWrapT = AttributeKey("textureWrapT")
  static let textureIntensity = AttributeKey("textureIntensity")
  static let textureMinificationFilter = AttributeKey("textureMinificationFilter")
  static let textureMagnificationFilter = AttributeKey("textureMagnificationFilter")
  // Texture modifiers (applying textures to materials)
  static let skDiffuseTexture = AttributeKey("skDiffuseTexture")
  static let skSpecularTexture = AttributeKey("skSpecularTexture")
  static let skEmissionTexture = AttributeKey("skEmissionTexture")
  static let skNormalTexture = AttributeKey("skNormalTexture")
  static let skRoughnessTexture = AttributeKey("skRoughnessTexture")
  static let skMetalnessTexture = AttributeKey("skMetalnessTexture")
  static let skAmbientOcclusionTexture = AttributeKey("skAmbientOcclusionTexture")

  static func custom(_ value: String) -> AttributeKey {
    AttributeKey(value)
  }
}
